/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as MorphGradientImport } from './routes/morph-gradient'
import { Route as IndexImport } from './routes/index'

// Create/Update Routes

const MorphGradientRoute = MorphGradientImport.update({
  id: '/morph-gradient',
  path: '/morph-gradient',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/morph-gradient': {
      id: '/morph-gradient'
      path: '/morph-gradient'
      fullPath: '/morph-gradient'
      preLoaderRoute: typeof MorphGradientImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/morph-gradient': typeof MorphGradientRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/morph-gradient': typeof MorphGradientRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/morph-gradient': typeof MorphGradientRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/morph-gradient'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/morph-gradient'
  id: '__root__' | '/' | '/morph-gradient'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  MorphGradientRoute: typeof MorphGradientRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  MorphGradientRoute: MorphGradientRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/morph-gradient"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/morph-gradient": {
      "filePath": "morph-gradient.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
